# Generated by Django 5.1.5 on 2025-02-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0002_remove_certificate_image_remove_certificate_nameposx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=7),
        ),
    ]
