# Generated by Django 5.1.5 on 2025-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0003_certificate_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycenter',
            name='location',
            field=models.URLField(max_length=400),
        ),
    ]
