# Generated by Django 5.1.5 on 2025-02-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_center', '0004_alter_studycenter_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studycenter',
            name='location',
            field=models.URLField(max_length=1000),
        ),
    ]
